version: '3.9'

services:
  db:
    image: postgres:13-alpine
    container_name: Torneo_VanRossum
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - /var/lib/postgres/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PG_PORT}
    ports:
      - 8080:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db